export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const METRICS_RECEIVED = "METRICS_RECEIVED";
export const METRIC_SELECTED = "METRIC_SELECTED";
export const METRIC_DESELECTED = "METRIC_DESELECTED";
export const SELECTED_MEASUREMENTS = "SELECTED_MEASUREMENTS";
